'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Fonctionnalité Enregistrement automatique My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lExpertMode() As Boolean
            Get
                Return CType(Me("lExpertMode"),Boolean)
            End Get
            Set
                Me("lExpertMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property IndLangue() As Integer
            Get
                Return CType(Me("IndLangue"),Integer)
            End Get
            Set
                Me("IndLangue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property IndLangueNDC() As Integer
            Get
                Return CType(Me("IndLangueNDC"),Integer)
            End Get
            Set
                Me("IndLangueNDC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property indUnitDimension() As Integer
            Get
                Return CType(Me("indUnitDimension"),Integer)
            End Get
            Set
                Me("indUnitDimension") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lJuridique() As Boolean
            Get
                Return CType(Me("lJuridique"),Boolean)
            End Get
            Set
                Me("lJuridique") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property RecentFiles() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("RecentFiles"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("RecentFiles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property indUnitLongueur() As Integer
            Get
                Return CType(Me("indUnitLongueur"),Integer)
            End Get
            Set
                Me("indUnitLongueur") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property indUnitContraintes() As Integer
            Get
                Return CType(Me("indUnitContraintes"),Integer)
            End Get
            Set
                Me("indUnitContraintes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property indUnitModuleY() As Integer
            Get
                Return CType(Me("indUnitModuleY"),Integer)
            End Get
            Set
                Me("indUnitModuleY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.00")>  _
        Public Property GammaMZero() As Decimal
            Get
                Return CType(Me("GammaMZero"),Decimal)
            End Get
            Set
                Me("GammaMZero") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
        Public Property GammaM1() As Decimal
            Get
                Return CType(Me("GammaM1"),Decimal)
            End Get
            Set
                Me("GammaM1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.25")>  _
        Public Property GammaM2() As Decimal
            Get
                Return CType(Me("GammaM2"),Decimal)
            End Get
            Set
                Me("GammaM2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.5")>  _
        Public Property GammaC() As Decimal
            Get
                Return CType(Me("GammaC"),Decimal)
            End Get
            Set
                Me("GammaC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.15")>  _
        Public Property GammaS() As Decimal
            Get
                Return CType(Me("GammaS"),Decimal)
            End Get
            Set
                Me("GammaS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
        Public Property GammaP() As Decimal
            Get
                Return CType(Me("GammaP"),Decimal)
            End Get
            Set
                Me("GammaP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.25")>  _
        Public Property GammaVs() As Decimal
            Get
                Return CType(Me("GammaVs"),Decimal)
            End Get
            Set
                Me("GammaVs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.25")>  _
        Public Property GammaVc() As Decimal
            Get
                Return CType(Me("GammaVc"),Decimal)
            End Get
            Set
                Me("GammaVc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
        Public Property GammaM_fi() As Decimal
            Get
                Return CType(Me("GammaM_fi"),Decimal)
            End Get
            Set
                Me("GammaM_fi") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
        Public Property GammaC_fi() As Decimal
            Get
                Return CType(Me("GammaC_fi"),Decimal)
            End Get
            Set
                Me("GammaC_fi") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.5")>  _
        Public Property GammaV_fi() As Decimal
            Get
                Return CType(Me("GammaV_fi"),Decimal)
            End Get
            Set
                Me("GammaV_fi") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.35")>  _
        Public Property GammaG_sup() As Decimal
            Get
                Return CType(Me("GammaG_sup"),Decimal)
            End Get
            Set
                Me("GammaG_sup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
        Public Property GammaG_inf() As Decimal
            Get
                Return CType(Me("GammaG_inf"),Decimal)
            End Get
            Set
                Me("GammaG_inf") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.5")>  _
        Public Property GammaQ() As Decimal
            Get
                Return CType(Me("GammaQ"),Decimal)
            End Get
            Set
                Me("GammaQ") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.7")>  _
        Public Property Psi0_Q1() As Decimal
            Get
                Return CType(Me("Psi0_Q1"),Decimal)
            End Get
            Set
                Me("Psi0_Q1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.5")>  _
        Public Property Psi1_Q1() As Decimal
            Get
                Return CType(Me("Psi1_Q1"),Decimal)
            End Get
            Set
                Me("Psi1_Q1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.3")>  _
        Public Property Psi2_Q1() As Decimal
            Get
                Return CType(Me("Psi2_Q1"),Decimal)
            End Get
            Set
                Me("Psi2_Q1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lGammaV_unique() As Boolean
            Get
                Return CType(Me("lGammaV_unique"),Boolean)
            End Get
            Set
                Me("lGammaV_unique") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property indUnitEffort() As Integer
            Get
                Return CType(Me("indUnitEffort"),Integer)
            End Get
            Set
                Me("indUnitEffort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property indUnitMoment() As Integer
            Get
                Return CType(Me("indUnitMoment"),Integer)
            End Get
            Set
                Me("indUnitMoment") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.00")>  _
        Public Property EtaW() As Decimal
            Get
                Return CType(Me("EtaW"),Decimal)
            End Get
            Set
                Me("EtaW") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserName() As String
            Get
                Return CType(Me("UserName"),String)
            End Get
            Set
                Me("UserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CompanyName() As String
            Get
                Return CType(Me("CompanyName"),String)
            End Get
            Set
                Me("CompanyName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lNdCDispLoadCase() As Boolean
            Get
                Return CType(Me("lNdCDispLoadCase"),Boolean)
            End Get
            Set
                Me("lNdCDispLoadCase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lNdCShowDiagram() As Boolean
            Get
                Return CType(Me("lNdCShowDiagram"),Boolean)
            End Get
            Set
                Me("lNdCShowDiagram") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lNdCDispFM_ELU() As Boolean
            Get
                Return CType(Me("lNdCDispFM_ELU"),Boolean)
            End Get
            Set
                Me("lNdCDispFM_ELU") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lNdCDispFM_ELS() As Boolean
            Get
                Return CType(Me("lNdCDispFM_ELS"),Boolean)
            End Get
            Set
                Me("lNdCDispFM_ELS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lNdCDispFM_ELF() As Boolean
            Get
                Return CType(Me("lNdCDispFM_ELF"),Boolean)
            End Get
            Set
                Me("lNdCDispFM_ELF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lNdCCourbeHivoss() As Boolean
            Get
                Return CType(Me("lNdCCourbeHivoss"),Boolean)
            End Get
            Set
                Me("lNdCCourbeHivoss") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lNdCDispSigmaCharges() As Boolean
            Get
                Return CType(Me("lNdCDispSigmaCharges"),Boolean)
            End Get
            Set
                Me("lNdCDispSigmaCharges") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lNdCDispMelMixte() As Boolean
            Get
                Return CType(Me("lNdCDispMelMixte"),Boolean)
            End Get
            Set
                Me("lNdCDispMelMixte") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.7")>  _
        Public Property Psi0_Q2() As Decimal
            Get
                Return CType(Me("Psi0_Q2"),Decimal)
            End Get
            Set
                Me("Psi0_Q2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.5")>  _
        Public Property Psi1_Q2() As Decimal
            Get
                Return CType(Me("Psi1_Q2"),Decimal)
            End Get
            Set
                Me("Psi1_Q2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.3")>  _
        Public Property Psi2_Q2() As Decimal
            Get
                Return CType(Me("Psi2_Q2"),Decimal)
            End Get
            Set
                Me("Psi2_Q2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property PorteeMin() As Decimal
            Get
                Return CType(Me("PorteeMin"),Decimal)
            End Get
            Set
                Me("PorteeMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25")>  _
        Public Property PorteeMax() As Decimal
            Get
                Return CType(Me("PorteeMax"),Decimal)
            End Get
            Set
                Me("PorteeMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.5")>  _
        Public Property PorteeConsoleMin() As Decimal
            Get
                Return CType(Me("PorteeConsoleMin"),Decimal)
            End Get
            Set
                Me("PorteeConsoleMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.3")>  _
        Public Property RatioPorteeConsoleMax() As Decimal
            Get
                Return CType(Me("RatioPorteeConsoleMax"),Decimal)
            End Get
            Set
                Me("RatioPorteeConsoleMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property ThetaH() As Decimal
            Get
                Return CType(Me("ThetaH"),Decimal)
            End Get
            Set
                Me("ThetaH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.1")>  _
        Public Property EpDallePleineMin() As Decimal
            Get
                Return CType(Me("EpDallePleineMin"),Decimal)
            End Get
            Set
                Me("EpDallePleineMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.4")>  _
        Public Property RatioEpRenformisMax() As Decimal
            Get
                Return CType(Me("RatioEpRenformisMax"),Decimal)
            End Get
            Set
                Me("RatioEpRenformisMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.05")>  _
        Public Property EpDalleMixteMin() As Decimal
            Get
                Return CType(Me("EpDalleMixteMin"),Decimal)
            End Get
            Set
                Me("EpDalleMixteMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1500")>  _
        Public Property RhoCBetonLegerMin() As Decimal
            Get
                Return CType(Me("RhoCBetonLegerMin"),Decimal)
            End Get
            Set
                Me("RhoCBetonLegerMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2200")>  _
        Public Property RhoCBetonLegerMax() As String
            Get
                Return CType(Me("RhoCBetonLegerMax"),String)
            End Get
            Set
                Me("RhoCBetonLegerMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Norme() As Integer
            Get
                Return CType(Me("Norme"),Integer)
            End Get
            Set
                Me("Norme") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lLargeurEfficaceSimplifiee() As Boolean
            Get
                Return CType(Me("lLargeurEfficaceSimplifiee"),Boolean)
            End Get
            Set
                Me("lLargeurEfficaceSimplifiee") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lCompressionArma() As Boolean
            Get
                Return CType(Me("lCompressionArma"),Boolean)
            End Get
            Set
                Me("lCompressionArma") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("210000")>  _
        Public Property EsArmatures() As Decimal
            Get
                Return CType(Me("EsArmatures"),Decimal)
            End Get
            Set
                Me("EsArmatures") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
        Public Property dMaxNodes() As Decimal
            Get
                Return CType(Me("dMaxNodes"),Decimal)
            End Get
            Set
                Me("dMaxNodes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property nbMinNodesConsole() As Integer
            Get
                Return CType(Me("nbMinNodesConsole"),Integer)
            End Get
            Set
                Me("nbMinNodesConsole") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property nbMinNodesTravee() As Integer
            Get
                Return CType(Me("nbMinNodesTravee"),Integer)
            End Get
            Set
                Me("nbMinNodesTravee") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.10")>  _
        Public Property PsiLPermanent() As Decimal
            Get
                Return CType(Me("PsiLPermanent"),Decimal)
            End Get
            Set
                Me("PsiLPermanent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.55")>  _
        Public Property PsiLRetrait() As Decimal
            Get
                Return CType(Me("PsiLRetrait"),Decimal)
            End Get
            Set
                Me("PsiLRetrait") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property AgeT0SH_Dalle() As Integer
            Get
                Return CType(Me("AgeT0SH_Dalle"),Integer)
            End Get
            Set
                Me("AgeT0SH_Dalle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property AgeT0SH_Enrobage() As Integer
            Get
                Return CType(Me("AgeT0SH_Enrobage"),Integer)
            End Get
            Set
                Me("AgeT0SH_Enrobage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("28")>  _
        Public Property AgeT0G1_Dalle() As Integer
            Get
                Return CType(Me("AgeT0G1_Dalle"),Integer)
            End Get
            Set
                Me("AgeT0G1_Dalle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("56")>  _
        Public Property AgeT0G1_Enrobage() As Integer
            Get
                Return CType(Me("AgeT0G1_Enrobage"),Integer)
            End Get
            Set
                Me("AgeT0G1_Enrobage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("28")>  _
        Public Property AgeT0G2_Dalle() As Integer
            Get
                Return CType(Me("AgeT0G2_Dalle"),Integer)
            End Get
            Set
                Me("AgeT0G2_Dalle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("56")>  _
        Public Property AgeT0G2_Enrobage() As Integer
            Get
                Return CType(Me("AgeT0G2_Enrobage"),Integer)
            End Get
            Set
                Me("AgeT0G2_Enrobage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lDessNumeros_CDC() As Boolean
            Get
                Return CType(Me("lDessNumeros_CDC"),Boolean)
            End Get
            Set
                Me("lDessNumeros_CDC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lDessCharges_CDC() As Boolean
            Get
                Return CType(Me("lDessCharges_CDC"),Boolean)
            End Get
            Set
                Me("lDessCharges_CDC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lDessInerties_CDC() As Boolean
            Get
                Return CType(Me("lDessInerties_CDC"),Boolean)
            End Get
            Set
                Me("lDessInerties_CDC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lDessEffortT_CDC() As Boolean
            Get
                Return CType(Me("lDessEffortT_CDC"),Boolean)
            End Get
            Set
                Me("lDessEffortT_CDC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lDessMoment_CDC() As Boolean
            Get
                Return CType(Me("lDessMoment_CDC"),Boolean)
            End Get
            Set
                Me("lDessMoment_CDC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lDessDeformee_CDC() As Boolean
            Get
                Return CType(Me("lDessDeformee_CDC"),Boolean)
            End Get
            Set
                Me("lDessDeformee_CDC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lDessValEnv_CDC() As Boolean
            Get
                Return CType(Me("lDessValEnv_CDC"),Boolean)
            End Get
            Set
                Me("lDessValEnv_CDC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lDessNumeros_ELU() As Boolean
            Get
                Return CType(Me("lDessNumeros_ELU"),Boolean)
            End Get
            Set
                Me("lDessNumeros_ELU") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lDessCharges_ELU() As Boolean
            Get
                Return CType(Me("lDessCharges_ELU"),Boolean)
            End Get
            Set
                Me("lDessCharges_ELU") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lDessInerties_ELU() As Boolean
            Get
                Return CType(Me("lDessInerties_ELU"),Boolean)
            End Get
            Set
                Me("lDessInerties_ELU") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lDessEffortT_ELU() As Boolean
            Get
                Return CType(Me("lDessEffortT_ELU"),Boolean)
            End Get
            Set
                Me("lDessEffortT_ELU") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lDessMoment_ELU() As Boolean
            Get
                Return CType(Me("lDessMoment_ELU"),Boolean)
            End Get
            Set
                Me("lDessMoment_ELU") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lDessDeformee_ELU() As Boolean
            Get
                Return CType(Me("lDessDeformee_ELU"),Boolean)
            End Get
            Set
                Me("lDessDeformee_ELU") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lDessValEnv_ELU() As Boolean
            Get
                Return CType(Me("lDessValEnv_ELU"),Boolean)
            End Get
            Set
                Me("lDessValEnv_ELU") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lDessNumeros_ELF() As Boolean
            Get
                Return CType(Me("lDessNumeros_ELF"),Boolean)
            End Get
            Set
                Me("lDessNumeros_ELF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lDessCharges_ELF() As Boolean
            Get
                Return CType(Me("lDessCharges_ELF"),Boolean)
            End Get
            Set
                Me("lDessCharges_ELF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lDessInerties_ELF() As Boolean
            Get
                Return CType(Me("lDessInerties_ELF"),Boolean)
            End Get
            Set
                Me("lDessInerties_ELF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lDessEffortT_ELF() As Boolean
            Get
                Return CType(Me("lDessEffortT_ELF"),Boolean)
            End Get
            Set
                Me("lDessEffortT_ELF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lDessMoment_ELF() As Boolean
            Get
                Return CType(Me("lDessMoment_ELF"),Boolean)
            End Get
            Set
                Me("lDessMoment_ELF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lDessDeformee_ELF() As Boolean
            Get
                Return CType(Me("lDessDeformee_ELF"),Boolean)
            End Get
            Set
                Me("lDessDeformee_ELF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lDessValEnv_ELF() As Boolean
            Get
                Return CType(Me("lDessValEnv_ELF"),Boolean)
            End Get
            Set
                Me("lDessValEnv_ELF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lDessNumeros_ELS() As Boolean
            Get
                Return CType(Me("lDessNumeros_ELS"),Boolean)
            End Get
            Set
                Me("lDessNumeros_ELS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lDessCharges_ELS() As Boolean
            Get
                Return CType(Me("lDessCharges_ELS"),Boolean)
            End Get
            Set
                Me("lDessCharges_ELS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lDessInerties_ELS() As Boolean
            Get
                Return CType(Me("lDessInerties_ELS"),Boolean)
            End Get
            Set
                Me("lDessInerties_ELS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lDessEffortT_ELS() As Boolean
            Get
                Return CType(Me("lDessEffortT_ELS"),Boolean)
            End Get
            Set
                Me("lDessEffortT_ELS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lDessMoment_ELS() As Boolean
            Get
                Return CType(Me("lDessMoment_ELS"),Boolean)
            End Get
            Set
                Me("lDessMoment_ELS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lDessDeformee_ELS() As Boolean
            Get
                Return CType(Me("lDessDeformee_ELS"),Boolean)
            End Get
            Set
                Me("lDessDeformee_ELS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lDessValEnv_ELS() As Boolean
            Get
                Return CType(Me("lDessValEnv_ELS"),Boolean)
            End Get
            Set
                Me("lDessValEnv_ELS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.5")>  _
        Public Property RatioEpPredalleMax() As Decimal
            Get
                Return CType(Me("RatioEpPredalleMax"),Decimal)
            End Get
            Set
                Me("RatioEpPredalleMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property NbMaxiEtaisP() As Integer
            Get
                Return CType(Me("NbMaxiEtaisP"),Integer)
            End Get
            Set
                Me("NbMaxiEtaisP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.650")>  _
        Public Property hslimmax() As Decimal
            Get
                Return CType(Me("hslimmax"),Decimal)
            End Get
            Set
                Me("hslimmax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.05")>  _
        Public Property bappmin() As Decimal
            Get
                Return CType(Me("bappmin"),Decimal)
            End Get
            Set
                Me("bappmin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.01")>  _
        Public Property tpinfmin() As Decimal
            Get
                Return CType(Me("tpinfmin"),Decimal)
            End Get
            Set
                Me("tpinfmin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.01")>  _
        Public Property deltaCDev() As Decimal
            Get
                Return CType(Me("deltaCDev"),Decimal)
            End Get
            Set
                Me("deltaCDev") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
        Public Property GammaS_fi() As Decimal
            Get
                Return CType(Me("GammaS_fi"),Decimal)
            End Get
            Set
                Me("GammaS_fi") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property lNdCShowFMTables() As Boolean
            Get
                Return CType(Me("lNdCShowFMTables"),Boolean)
            End Get
            Set
                Me("lNdCShowFMTables") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lNdCShowFMEnveloppes() As Boolean
            Get
                Return CType(Me("lNdCShowFMEnveloppes"),Boolean)
            End Get
            Set
                Me("lNdCShowFMEnveloppes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property indUnitWModule() As Integer
            Get
                Return CType(Me("indUnitWModule"),Integer)
            End Get
            Set
                Me("indUnitWModule") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property indUnitInertie() As Integer
            Get
                Return CType(Me("indUnitInertie"),Integer)
            End Get
            Set
                Me("indUnitInertie") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lControlWebVersion() As Boolean
            Get
                Return CType(Me("lControlWebVersion"),Boolean)
            End Get
            Set
                Me("lControlWebVersion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lControlWebFichier() As Boolean
            Get
                Return CType(Me("lControlWebFichier"),Boolean)
            End Get
            Set
                Me("lControlWebFichier") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2000")>  _
        Public Property RhoCBetonNormalMin() As Decimal
            Get
                Return CType(Me("RhoCBetonNormalMin"),Decimal)
            End Get
            Set
                Me("RhoCBetonNormalMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.0075")>  _
        Public Property Twcdmin() As Decimal
            Get
                Return CType(Me("Twcdmin"),Decimal)
            End Get
            Set
                Me("Twcdmin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property FrmMainSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("FrmMainSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("FrmMainSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property FrmMainLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("FrmMainLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("FrmMainLocation") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.PMXInterface.My.MySettings
            Get
                Return Global.PMXInterface.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
