Public Class Cls_CALCUL_MODAL

#Region " VARIABLES INTERNES "
    Dim MAT As MATERIAU
    Dim NOEUDS As STR_NOEUDS
    Dim BARRES As STR_BARRES
    Dim MASSES As MAS_BARRES
    Dim RESOLUTION As MOD_RESOLUTION
    Dim RESULTATS As MOD_RESULTATS
#End Region


End Class
